# Generated by Django 5.2.4 on 2025-08-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0011_alter_adminlog_options_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_phone',
            field=models.CharField(blank=True, help_text="Customer's phone number", max_length=20, null=True),
        ),
    ]
