# Generated by Django 5.2.4 on 2025-08-09 19:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0012_invoice_customer_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, help_text='Rate to be applied to amount for pricing calculation', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True)),
                ('customer_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, help_text="Customer's phone number", max_length=20, null=True)),
                ('date_of_sale', models.DateField(blank=True, db_index=True, default=django.utils.timezone.now, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, db_index=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='paid', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_of_sale', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Base amount for rate calculation', max_digits=12, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Rate applied to amount', max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales_app.cashinvoice')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='cashinvoice',
            index=models.Index(fields=['date_of_sale', 'payment_status'], name='sales_app_c_date_of_b311f0_idx'),
        ),
        migrations.AddIndex(
            model_name='cashinvoice',
            index=models.Index(fields=['customer_name', 'date_of_sale'], name='sales_app_c_custome_7238b6_idx'),
        ),
        migrations.AddIndex(
            model_name='cashinvoice',
            index=models.Index(fields=['user', 'date_of_sale'], name='sales_app_c_user_id_081392_idx'),
        ),
        migrations.AddIndex(
            model_name='cashsale',
            index=models.Index(fields=['invoice', 'item'], name='sales_app_c_invoice_2153ea_idx'),
        ),
    ]
