# Generated by Django 5.2.4 on 2025-08-09 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0002_expensecategory_taxsettings_accountingauditlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=100)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('total_quantity_sold', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, help_text='Revenue minus cost', max_digits=12)),
                ('average_selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('number_of_sales', models.IntegerField(default=0, help_text='Number of individual sales transactions')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_revenue', '-total_quantity_sold'],
                'indexes': [models.Index(fields=['product_name', 'period_start'], name='accounting__product_272506_idx'), models.Index(fields=['total_revenue'], name='accounting__total_r_47fa19_idx'), models.Index(fields=['total_quantity_sold'], name='accounting__total_q_4ee0f8_idx')],
                'unique_together': {('product_name', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='SalesPersonPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('total_sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_invoices', models.IntegerField(default=0)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('average_sale_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of successful sales', max_digits=5)),
                ('performance_rating', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('below_average', 'Below Average'), ('poor', 'Poor')], default='average', max_length=20)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_sales_amount', '-total_invoices'],
                'indexes': [models.Index(fields=['user', 'period_start'], name='accounting__user_id_92d361_idx'), models.Index(fields=['total_sales_amount'], name='accounting__total_s_382557_idx'), models.Index(fields=['performance_rating'], name='accounting__perform_0fb530_idx')],
                'unique_together': {('user', 'period_start', 'period_end')},
            },
        ),
    ]
