# Generated by Django 5.2.4 on 2025-08-16 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_app', '0003_productperformance_salespersonperformance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashServicePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(db_index=True, max_length=100)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('total_amount_processed', models.DecimalField(decimal_places=2, default=0, help_text='Total amount processed (base amount)', max_digits=12)),
                ('total_revenue_generated', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue from rates', max_digits=12)),
                ('transaction_count', models.IntegerField(default=0)),
                ('average_transaction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_rate_applied', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_revenue_generated', '-total_amount_processed'],
                'indexes': [models.Index(fields=['service_name', 'period_start'], name='accounting__service_a3dd2a_idx'), models.Index(fields=['total_revenue_generated'], name='accounting__total_r_5ba595_idx'), models.Index(fields=['transaction_count'], name='accounting__transac_11180d_idx')],
                'unique_together': {('service_name', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentFinancialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('regular_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('regular_invoices_count', models.IntegerField(default=0)),
                ('regular_paid_invoices', models.IntegerField(default=0)),
                ('regular_outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_invoices_count', models.IntegerField(default=0)),
                ('cash_transactions_count', models.IntegerField(default=0)),
                ('subscriber_withdrawals_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subscriber_withdrawals_count', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_start', '-period_end'],
                'indexes': [models.Index(fields=['period_type', 'period_start'], name='accounting__period__f07b6f_idx'), models.Index(fields=['total_revenue'], name='accounting__total_r_5747e1_idx'), models.Index(fields=['period_start', 'period_end'], name='accounting__period__bf57ef_idx')],
                'unique_together': {('period_type', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='CashDepartmentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('total_cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cash_invoices', models.IntegerField(default=0)),
                ('total_transactions', models.IntegerField(default=0, help_text='Number of cash sale items')),
                ('average_transaction_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subscriber_withdrawal_amount', models.DecimalField(decimal_places=2, default=0, help_text='Special tracking for subscriber withdrawals', max_digits=12)),
                ('subscriber_withdrawal_count', models.IntegerField(default=0)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_cash_amount', '-total_cash_invoices'],
                'indexes': [models.Index(fields=['user', 'period_start'], name='accounting__user_id_dfacdb_idx'), models.Index(fields=['total_cash_amount'], name='accounting__total_c_b31834_idx'), models.Index(fields=['subscriber_withdrawal_amount'], name='accounting__subscri_878463_idx')],
                'unique_together': {('user', 'period_start', 'period_end')},
            },
        ),
    ]
